### ISSUE TITLE
Update Gatling version

### ISSUE THREAD

**Issue by luigigubello** [mhjort/clojider-gatling-highcharts-reporter#3]
Hi 👋 thank you for this great library! I have scanned it using Snyk - just for checking if `log4j` is used as sub-dependency - and I have seen there are some packages vulnerable, introduced by `gatling-charts`. Updating `gatling-charts` to the last version (`3.7.4`) should fix every security issue in the dependencies. If there are no legacy reasons, would it be possible to update this library? (I can create a PR)

**Comment by mhjort** [comment]
@luigigubello Sorry forgot to reply to this. Latest version is already using `3.7.4`. So closing this one
